name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: "go.mod"

    - name: test
      run: go test -v ./

  staticcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: "go.mod"

    - uses: dominikh/staticcheck-action@288b4e28bae83c59f35f73651aeb5cab746a06fc #v1.4.0
      with:
        install-go: false
        version: "2023.1.5"
